/* verilator lint_off UNDRIVEN */
/* verilator lint_off UNUSEDSIGNAL */
/* Generated by Yosys 0.34 (git sha1 4a1b5599258, gcc 8.3.1 -fPIC -Os) */

module NEUROMORPHIC_X1_macro(CLKin, RSTin, EN, R_WB, DI, AD, SEL, DO, func_ack, TM, SM, ScanInCC, ScanInDL, ScanInDR, ScanOutCC, VDDC, VDDA, VSS, Iref, Vbias, Vcomp
, Bias_comp1, Bias_comp2, Ramp, Vcc_L, Vcc_Body, VCC_reset, VCC_set, VCC_wl_reset, VCC_wl_set, VCC_wl_read, VCC_read);
  input [31:0] AD;
  wire [31:0] AD;
  input Bias_comp1;
  wire Bias_comp1;
  input Bias_comp2;
  wire Bias_comp2;
  input CLKin;
  wire CLKin;
  input [31:0] DI;
  wire [31:0] DI;
  output [31:0] DO;
  wire [31:0] DO;
  input EN;
  wire EN;
  input Iref;
  wire Iref;
  input RSTin;
  wire RSTin;
  input R_WB;
  wire R_WB;
  input Ramp;
  wire Ramp;
  input [3:0] SEL;
  wire [3:0] SEL;
  input SM;
  wire SM;
  input ScanInCC;
  wire ScanInCC;
  input ScanInDL;
  wire ScanInDL;
  input ScanInDR;
  wire ScanInDR;
  output ScanOutCC;
  wire ScanOutCC;
  input TM;
  wire TM;
  input VCC_read;
  wire VCC_read;
  input VCC_reset;
  wire VCC_reset;
  input VCC_set;
  wire VCC_set;
  input VCC_wl_read;
  wire VCC_wl_read;
  input VCC_wl_reset;
  wire VCC_wl_reset;
  input VCC_wl_set;
  wire VCC_wl_set;
  inout VDDA;
  wire VDDA;
  inout VDDC;
  wire VDDC;
  inout VSS;
  wire VSS;
  input Vbias;
  wire Vbias;
  input Vcc_Body;
  wire Vcc_Body;
  input Vcc_L;
  wire Vcc_L;
  input Vcomp;
  wire Vcomp;
  output func_ack;
  wire func_ack;
endmodule

/* verilator lint_on UNUSEDSIGNAL */
/* verilator lint_on UNDRIVEN */

